# Generated by Django 2.2.1 on 2020-02-03 05:51

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('category', models.CharField(choices=[('earning', 'Earning'), ('saving', 'Saving'), ('investing', 'Investing'), ('credit-cards', 'Credit Cards'), ('credit-score', 'Credit Score'), ('debt', 'Debt'), ('mentality', 'Mentality'), ('interviews', 'Interviews')], max_length=20)),
                ('main_image', models.ImageField(help_text='<h3>Aspect ratio must be exactly 3:2 </br> i.e. 1200 x 800</h3>', upload_to='img', validators=[blog.models.validate_image])),
                ('inline_image_1', models.ImageField(blank=True, default=None, help_text='Optional', null=True, upload_to='img')),
                ('inline_image_2', models.ImageField(blank=True, default=None, help_text='Optional', null=True, upload_to='img')),
                ('inline_image_3', models.ImageField(blank=True, default=None, help_text='Optional', null=True, upload_to='img')),
                ('inline_image_4', models.ImageField(blank=True, default=None, help_text='Optional', null=True, upload_to='img')),
                ('inline_image_5', models.ImageField(blank=True, default=None, help_text='Optional', null=True, upload_to='img')),
                ('inline_image_6', models.ImageField(blank=True, default=None, help_text='Optional', null=True, upload_to='img')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('body_html', models.TextField(help_text="<h3> Use the following tags:</br> <xmp><p>Paragraph</p></xmp> <xmp><h1>Bold Header</h1></xmp> <xmp><h2>Quote</h2></xmp> <xmp><ul><li>Bullet Points</li></ul></xmp> <xmp><a href='https'>Link</a></xmp> <xmp><button><a href='https'>Button</a></button></xmp> <xmp><img1> - <img6></xmp> </h3>", verbose_name='body (HTML)')),
                ('published_date', models.DateTimeField(blank=True, default=None, help_text='<h3>Post will not be published until this field is set </br> *Leave blank for draft</h3>', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
    ]
