# Generated by Django 2.2.1 on 2019-07-04 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FRUGALITY', 'Frugality'), ('INVESTING', 'Investing'), ('CREDIT_CARDS', 'Credit Cards')], default='not set', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], default='not set', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
