# Generated by Django 2.2.1 on 2019-08-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('SAVING', 'Saving'), ('INVESTING', 'Investing'), ('CREDIT_CARDS', 'Credit Cards')], max_length=20),
        ),
    ]
