# Generated by Django 2.2.1 on 2019-07-27 01:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fb_post_embedded',
            field=models.TextField(default='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(help_text="<h3> Use the following tags:</br> <xmp><p>Paragraph</p></xmp> <xmp><h1>Bold Header</h1></xmp> <xmp><h2>Quote</h2></xmp> <xmp><ul><li>Bullet Points</li></ul></xmp> <xmp><a href='https' target='_blank'>Link</a></xmp> <xmp><button><a href='https' target='_blank'>Button</a></button></xmp> <xmp><img1> - <img6></xmp> </h3>", verbose_name='body (HTML)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(help_text='<h3>Aspect ratio must be exactly 3:2 </br> i.e. 1200 x 800</h3>', upload_to='img', validators=[blog.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=None, help_text='<h3>Post will not be published until this field is set </br> *Leave blank for draft</h3>', null=True),
        ),
    ]
