# Generated by Django 2.2.1 on 2020-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('earning', 'Earning'), ('saving', 'Saving'), ('investing', 'Investing'), ('credit-cards', 'Credit Cards'), ('credit-score', 'Credit Score'), ('debt', 'Debt'), ('mentality', 'Mentality'), ('interviews', 'Interviews')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
