# Generated by Django 2.2.1 on 2019-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190726_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fb_post_embedded',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
