# Generated by Django 2.2.1 on 2019-07-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190726_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fb_post_embedded',
            new_name='fb_post_embedded_code',
        ),
    ]
