# Generated by Django 2.2.1 on 2019-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190704_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=3),
        ),
    ]
