# Generated by Django 2.2.1 on 2019-07-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190726_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fb_post_embedded_code',
        ),
    ]
