# Generated by Django 2.2.1 on 2019-07-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190704_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
