# Generated by Django 2.2.1 on 2019-07-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='not set', help_text='Image must be 1200 x 800', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Image must be 1200 x 800', upload_to='blog/static/blog/img'),
        ),
    ]
