# Generated by Django 2.2.1 on 2019-07-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190705_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='article_image_1',
            field=models.ImageField(blank=True, help_text='Optional', upload_to='blog/static/blog/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image_2',
            field=models.ImageField(blank=True, help_text='Optional', upload_to='blog/static/blog/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image_3',
            field=models.ImageField(blank=True, help_text='Optional', upload_to='blog/static/blog/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image_4',
            field=models.ImageField(blank=True, help_text='Optional', upload_to='blog/static/blog/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image_5',
            field=models.ImageField(blank=True, help_text='Optional', upload_to='blog/static/blog/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_image_6',
            field=models.ImageField(blank=True, help_text='Optional', upload_to='blog/static/blog/img'),
        ),
    ]
