# Generated by Django 2.2.1 on 2019-07-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190705_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(default='not set', verbose_name='body (HTML)'),
            preserve_default=False,
        ),
    ]
