# Generated by Django 2.2.1 on 2019-07-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190705_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(help_text='Use the following html tags: p, h1, h2 (paragrah, bold text, quote)', verbose_name='body (HTML)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='<h3>This is required and image must be 1200 x 800</h3>', upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Post will not be published until this field is set (Leave blank for draft)', null=True),
        ),
    ]
