# Generated by Django 2.2.1 on 2019-07-12 04:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190705_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='inline_image_1',
            field=models.ImageField(default='not set', help_text='Optional. If used use <img1> in body', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='inline_image_2',
            field=models.ImageField(default='not set', help_text='Optional. If used use <img2> in body', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='inline_image_3',
            field=models.ImageField(default='not set', help_text='Optional. If used use <img3> in body', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='inline_image_4',
            field=models.ImageField(default='not set', help_text='Optional. If used use <img4> in body', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='inline_image_5',
            field=models.ImageField(default='not set', help_text='Optional. If used use <img5> in body', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='inline_image_6',
            field=models.ImageField(default='not set', help_text='Optional. If used use <img6> in body', upload_to='blog/static/blog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='not set', help_text='Image must be 1200 x 800', upload_to='blog/static/blog/img', validators=[blog.models.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(help_text='Use the following html tags:</br>h1:bold header</br>p:paragrah</br>h2:quote', verbose_name='body (HTML)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FRUGALITY', 'FRUGALITY'), ('INVESTING', 'INVESTING'), ('CREDIT_CARDS', 'CREDIT CARDS')], max_length=20),
        ),
    ]
