# Generated by Django 2.2.1 on 2019-07-12 05:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190711_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='inline_image_1',
            field=models.ImageField(blank=True, default=None, help_text='Optional. If used use <img1> in body', null=True, upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_image_2',
            field=models.ImageField(blank=True, default=None, help_text='Optional. If used use <img2> in body', null=True, upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_image_3',
            field=models.ImageField(blank=True, default=None, help_text='Optional. If used use <img3> in body', null=True, upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_image_4',
            field=models.ImageField(blank=True, default=None, help_text='Optional. If used use <img4> in body', null=True, upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_image_5',
            field=models.ImageField(blank=True, default=None, help_text='Optional. If used use <img5> in body', null=True, upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_image_6',
            field=models.ImageField(blank=True, default=None, help_text='Optional. If used use <img6> in body', null=True, upload_to='blog/static/blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(help_text='Required. Image must be 1200 x 800', upload_to='blog/static/blog/img', validators=[blog.models.validate_image]),
        ),
    ]
